# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: ckunimur <ckunimur@student.42sp.org.br>    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/05/13 11:45:27 by ckunimur          #+#    #+#              #
#    Updated: 2023/05/13 11:49:33 by ckunimur         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = strcpy

SRC = strcpy.c

FLAGS = -Wall -Werror -Wextra

test:
	gcc $(SRC) $(FLAGS) -o $(NAME)

	./$(NAME)

clean:
	rm -f $(NAME)