# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: ckunimur <ckunimur@student.42sp.org.br>    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/06/20 13:11:34 by ckunimur          #+#    #+#              #
#    Updated: 2023/06/20 13:13:06 by ckunimur         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = is_power_of_2

SRC = is_power_of_2.c

FLAGS = -Wall -Werror -Wextra

test:
	gcc -g $(SRC) $(FLAGS) -o $(NAME)

fclean:
	rm -rf $(NAME)
