# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: ckunimur <ckunimur@student.42sp.org.br>    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/05/13 11:08:57 by ckunimur          #+#    #+#              #
#    Updated: 2023/05/13 11:15:29 by ckunimur         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = fizzbuzz

SRC = fizzbuzz.c

FLAGS = -Wextra -Wall -Werror

test: 
	gcc $(FLAGS) $(SRC) -o $(NAME)

	./$(NAME)

clean:
	rm -f $(NAME)